# Generated by Django 3.2.7 on 2021-09-04 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LipaNaMpesaOnline',
            fields=[
                ('MerchantRequestID', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=255, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('Amount', models.FloatField(blank=True, default=0, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('TransactionDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=13, null=True)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
