# Generated by Django 3.2.6 on 2021-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='Amount',
            field=models.FloatField(default=0),
        ),
    ]
