# Generated by Django 3.2.6 on 2021-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_lipanampesaonline_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='Amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='ResultCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipanampesaonline',
            name='TransactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
