# Generated by Django 3.2.6 on 2021-09-01 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_auto_20210901_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipanampesaonline',
            name='id',
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
