# Generated by Django 3.2.5 on 2021-08-26 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, default='staticImages/default-placeholder.png', null=True, upload_to='product/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Product Images',
            },
        ),
    ]
