

export const GALLERY_LIST_REQUEST = 'GALLERY_LIST_REQUEST'
export const GALLERY_LIST_SUCCESS = 'GALLERY_LIST_SUCCESS'
export const GALLERY_LIST_FAIL = 'GALLERY_LIST_FAIL'
export const GALLERY_LIST_RESET = 'GALLERY_LIST_RESET'